language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli istanbul spider-script
after_success:
- istanbul cover -x lib/parser.js ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
